version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=gamescatalog;Username=postgres;Password=example
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: gamescatalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
